version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env.example

  frontend:
    build:
      context: .
      dockerfile: infrastructure/docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
